### ISSUE TITLE
Doesn't report covered Vars

### ISSUE THREAD

**Issue by JeffryBooher** [peol/brackets-eslint#12] opened 2015-02-18 17:49 UTC
This extension does not report vars covered by child-scope.

```javascript
var comp,
     activeComp = _.find(document.comps, function (comp) {
            return comp.appearance;
     });
```

It only reports the no-unused-vars error on line 1 it does not report the no-shadow error on line 2 even though this is not turned off in my .eslintrc file:

```json
{
    "env": {
        "node": true
    },
    "rules": {
        "no-underscore-dangle": 0,
        "no-multi-spaces": 0,
        "no-trailing-spaces": 0
    }
}
```

**Comment by peol** [comment] 2015-02-18 22:25
This extension doesn't modify ESLint in any way, I can't see how that's an extension issue. If you use ESLint version `0.14.1` in CLI, does it warn? Do you have any inherited `.eslintrc` settings?

**Comment by JeffryBooher** [comment] 2015-02-18 22:27
no inherited settings.  i'm using it straight out of the box -- are you installing your own node modules or relying on what the user has installed globally?

**Comment by JeffryBooher** [comment] 2015-02-18 22:33
I see the extension is dependant on eslint "^0.14.1";  so i'm not sure why it doesn't report the error.  I switched to another Brackets ES Lint extension that does report the error -- his is dependant on "0.14.x" ; not sure why his reports it and yours doesn't.

**Comment by JeffryBooher** [comment] 2015-02-18 22:39
BTW: I'm reporting this from the Gulp ESLint plugin (gulp.eslint) that depends on ESLint "^0.13.0" still not sure why yours doesn't report it. Gulp is using 0.13.0, the ES Lint extension that reports the error is using ESLint 0.14.1 as is yours.  You might give it a try and see if you can reproduce the error.

**Comment by peol** [comment] 2015-02-18 22:41
I just tried it locally, mine does warn:
`     activeComp = _.find(document.comps, function (comp) {`
`

**Comment by peol** [comment] 2015-02-19 20:36
Since I cannot reproduce and I cannot see a reason why it shouldn't work (since we're basically just feeding ESLint options and get a list of errors back), I'm closing this. If you have additional info that might make it reproducible, feel free to update/re-open this issue.

**Closed by peol** 2015-02-19 20:36 UTC
